//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CochesCutres
{
    using System;
    using System.Collections.Generic;
    
    public partial class operacionesCompraVenta
    {
        public int IdOperacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string TipoOperacion { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<double> Precio { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual vehiculos vehiculos { get; set; }
    }
}
