//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CochesCutres
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehiculos()
        {
            this.operacionesCompraVenta = new HashSet<operacionesCompraVenta>();
        }
    
        public int IdVehiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> NumPuertas { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Kilometros { get; set; }
        public string TipoVehiculo { get; set; }
        public Nullable<int> MesesGarantia { get; set; }
        public Nullable<bool> EstaStock { get; set; }
        public byte[] Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operacionesCompraVenta> operacionesCompraVenta { get; set; }
    }
}
